pipeline {
    agent any
    environment {
        // Cập nhật PATH với đường dẫn của Python nếu đã cài sẵn
        PATH = "C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312;${env.PATH}"
    }

    stages {
        stage('Check Python & Pip') {
            steps {
                // Kiểm tra nếu Python và Pip đã có trong PATH
                bat 'python --version'
                bat 'pip --version'
            }
        }

        stage('Install Requirements') {
            steps {
                bat 'pip install -r s05\\python-simple-app\\requirements.txt'
            }
        }

        stage('Run Application') {
            steps {
                bat 'start /B python s05\\python-simple-app\\app.py'
            }
        }

        stage('Test Application') {
            steps {
                bat 'timeout /t 10 && curl -s http://localhost:8000'
            }
        }

        stage('Cleanup') {
            steps {
                // Dừng ứng dụng bằng cách tìm và kết thúc tiến trình
                bat 'for /f "tokens=5" %a in (\'netstat -ano ^| findstr :8000\') do taskkill /F /PID %a'
            }
        }
    }
}
