pipeline {
    agent any
    stages {
        stage('Install Python & Pip') {
            steps {
                // Kiểm tra nếu Python đã được cài đặt
                bat 'python --version || (echo Installing Python... && powershell -command "Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.12.0/python-3.12.0-amd64.exe -OutFile python-installer.exe; Start-Process python-installer.exe -ArgumentList \'/quiet InstallAllUsers=1 PrependPath=1\' -Wait; del python-installer.exe")'
                
                // Kiểm tra nếu Pip đã được cài đặt
                bat 'pip --version || (echo Installing Pip... && python -m ensurepip --upgrade)'
            }
        }

        stage('build') {
            steps {
                bat 'pip install -r s05\\python-simple-app\\requirements.txt'
            }
        }

        stage('run') {
            steps {
                bat 'start /B python s05\\python-simple-app\\app.py'
            }
        }

        stage('test') {
            steps {
                bat 'timeout /t 60 && curl -s localhost:8000'
            }
        }

        stage('cleanup') {
            steps {
                bat 'taskkill /F /PID (netstat -ano | findstr ":8000" | findstr /R "[0-9]*$")'
            }
        }
    }
}
