pipeline {
   agent any
    environment {
        PYTHON_PATH = 'C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python312'
        PATH = "${env.PATH};${env.PYTHON_PATH};${env.PYTHON_PATH}\\Scripts"
    }
    stages {
        stage('Check Python & Pip') {
            steps {
                bat 'python --version'
                bat 'pip --version'
            }
        }
        stage('build') {
            steps {
                sh 'pip3 install -r python-simple-app/requirements.txt'
            }
        }

        stage('run') {
            steps {
                sh 'python3 python-simple-app/app.py &'
            }
        }

        stage('test') {
            steps {
                sh 'sleep 60 && curl -s localhost:8000'
            }
        }

        stage('cleanup') {
            steps {
                sh 'fuser -k 8000/tcp'
            }
        }

    }
}